#!/usr/bin/env bash

actual() {
  mylexer "$1" | myparser | ./semant 2>&1
}

expected() {
  lexer "$1" | parser | semant 2>&1
}

green() {
  printf "\033[0;32m%s\033[0m\n" "$1"
}

red() {
  printf "\033[0;31m%s\033[0m\n" "$1"
}

yellow() {
  printf "\033[0;33m%s\033[0m\n" "$1"
}

do_make=true

while getopts "q" opt
do
    case $opt in
    (q) do_make=false ;;
    (*) printf "-q: skip \"make semant\"" && exit 1 ;;
    esac
done
shift $((OPTIND-1))

case $do_make in
  (true) make -j8 semant;;
esac

for input_cl in "$@"
do
    echo
    yellow "$input_cl"
    if [[ ! -f "$input_cl" ]]; then
        red "FILE NOT FOUND"
        continue;
    fi

    if diff -u --color \
             --label actual <(actual "$input_cl") \
             --label expected <(expected "$input_cl"); then
      green PASS
    else
      red FAIL
    fi
done

