#!/usr/bin/env bash
input_dir="$1"
file_cnt=$(ls $input_dir --sort size -r | grep cl$ | wc -l)
n="${2:-$file_cnt}"
echo "$input_dir: " FOUND "$file_cnt" FILES
echo
./test_one $(\
    ls $input_dir --sort size -r | grep cl$ \
    | head -n $n \
    | sed 's@^@'"$input_dir"'/@'\
)
