#!/usr/bin/env bash

red() {
  xargs printf "\033[0;31m%s\033[0m\n"
}

green() {
  xargs printf "\033[0;32m%s\033[0m\n"
}

make lexer

for cl in "$@"
do 
    input_cl="$cl"
    diff -u --color --label actual <(./lexer $input_cl) --label expected <(../../bin/lexer $input_cl)
    if [[ "$?" -eq 0 ]]; then
      echo PASS | green
    else
      echo FAILED | red
    fi
    ehco INPUT:" ${input_cl}"
done

